# Generated by Django 5.0.6 on 2024-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='id телеграма'),
        ),
    ]
