# Generated by Django 5.0.6 on 2024-07-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, help_text='Введите id, чтобы получать оповещения в телеграме', max_length=50, null=True, unique=True, verbose_name='id телеграма'),
        ),
    ]
